services:
  - type: web
    name: medicare
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn medicare_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: medicare_project.settings
      - key: PYTHON_VERSION
        value: 3.10
    env: python
